import { SyncOption } from "../types/types";
import { t } from "../lang/helpers";

export const GENERATOR_VIEW_TYPE = "sync-script-generator-view";

export const SYNC_OPTIONS: SyncOption[] = [
	{
		name: "accessToken",
		group: "",
		title: t("ACCESS_TOKEN_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("ACCESS_TOKEN_ROOT_WPS_DESC"),
		example: t("ACCESS_TOKEN_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "apiKey",
		group: "",
		title: t("API_KEY_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_ROOT_AIRTABLE_DESC"),
		example: t("API_KEY_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "apiKey",
		group: "",
		title: t("API_KEY_ROOT_NOTION_TITLE"),
		platforms: ["Notion"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_ROOT_NOTION_DESC"),
		example: t("API_KEY_ROOT_NOTION_EXAMPLE"),
	},
	{
		name: "apiKey",
		group: "",
		title: t("API_KEY_ROOT_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_ROOT_NOCODB_DESC"),
		example: t("API_KEY_ROOT_NOCODB_EXAMPLE"),
	},
	{
		name: "email",
		group: "",
		title: t("USER_EMAIL_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("USER_EMAIL_ROOT_BASEROW_DESC"),
		example: t("USER_EMAIL_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "password",
		group: "",
		title: t("USER_PASSWORD_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("USER_PASSWORD_ROOT_BASEROW_DESC"),
		example: t("USER_PASSWORD_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "apiKey",
		group: "",
		title: t("API_KEY_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_ROOT_BASEROW_DESC"),
		example: t("API_KEY_ROOT_BASEROW_EXAMPLE"),
	},

	{
		name: "apiKey",
		group: "",
		title: t("API_KEY_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_ROOT_VIKA_DESC"),
		example: t("API_KEY_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "appID",
		group: "",
		title: t("APP_ID_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_ID_ROOT_FEISHU_DESC"),
		example: t("APP_ID_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "appID",
		group: "",
		title: t("APP_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_ID_ROOT_DING_DESC"),
		example: t("APP_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "appID",
		group: "",
		title: t("APP_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_ID_ROOT_WPS_DESC"),
		example: t("APP_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "appID",
		group: "",
		title: t("APP_ID_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_ID_ROOT_LARK_DESC"),
		example: t("APP_ID_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "appKey",
		group: "",
		title: t("APP_KEY_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_KEY_ROOT_WPS_DESC"),
		example: t("APP_KEY_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "appSecret",
		group: "",
		title: t("APP_SECRET_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_SECRET_ROOT_FEISHU_DESC"),
		example: t("APP_SECRET_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "appSecret",
		group: "",
		title: t("APP_SECRET_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_SECRET_ROOT_DING_DESC"),
		example: t("APP_SECRET_ROOT_DING_EXAMPLE"),
	},
	{
		name: "appSecret",
		group: "",
		title: t("APP_SECRET_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_SECRET_ROOT_LARK_DESC"),
		example: t("APP_SECRET_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultAppToken",
		group: "",
		title: t("DEFAULT_APP_TOKEN_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_APP_TOKEN_ROOT_FEISHU_DESC"),
		example: t("DEFAULT_APP_TOKEN_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "defaultAppToken",
		group: "",
		title: t("DEFAULT_APP_TOKEN_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_APP_TOKEN_ROOT_LARK_DESC"),
		example: t("DEFAULT_APP_TOKEN_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultWorkspaceID",
		group: "",
		title: t("DEFAULT_WORKSPACE_ID_ROOT_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_WORKSPACE_ID_ROOT_NOCODB_DESC"),
		example: t("DEFAULT_WORKSPACE_ID_ROOT_NOCODB_EXAMPLE"),
	},
	{
		name: "defaultBaseID",
		group: "",
		title: t("DEFAULT_BASE_ID_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_BASE_ID_ROOT_AIRTABLE_DESC"),
		example: t("DEFAULT_BASE_ID_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "defaultBaseID",
		group: "",
		title: t("DEFAULT_BASE_ID_ROOT_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_BASE_ID_ROOT_NOCODB_DESC"),
		example: t("DEFAULT_BASE_ID_ROOT_NOCODB_EXAMPLE"),
	},
	{
		name: "defaultBaseID",
		group: "",
		title: t("DEFAULT_BASE_ID_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_BASE_ID_ROOT_BASEROW_DESC"),
		example: t("DEFAULT_BASE_ID_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "defaultBaseID",
		group: "",
		title: t("DEFAULT_BASE_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_BASE_ID_ROOT_DING_DESC"),
		example: t("DEFAULT_BASE_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "defaultFileID",
		group: "",
		title: t("DEFAULT_FILE_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_FILE_ID_ROOT_WPS_DESC"),
		example: t("DEFAULT_FILE_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "defaultSheetID",
		group: "",
		title: t("DEFAULT_SHEET_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_SHEET_ID_ROOT_DING_DESC"),
		example: t("DEFAULT_SHEET_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "defaultSheetID",
		group: "",
		title: t("DEFAULT_SHEET_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_SHEET_ID_ROOT_WPS_DESC"),
		example: t("DEFAULT_SHEET_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_AIRTABLE_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "defaultDataSourceID",
		group: "",
		title: t("DEFAULT_DATA_SOURCE_ID_ROOT_NOTION_TITLE"),
		platforms: ["Notion"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_DATA_SOURCE_ID_ROOT_NOTION_DESC"),
		example: t("DEFAULT_DATA_SOURCE_ID_ROOT_NOTION_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_BASEROW_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_NOCODB_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_NOCODB_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_FEISHU_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_VIKA_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "defaultTableID",
		group: "",
		title: t("DEFAULT_TABLE_ID_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_TABLE_ID_ROOT_LARK_DESC"),
		example: t("DEFAULT_TABLE_ID_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultViewID",
		group: "",
		title: t("DEFAULT_VIEW_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DEFAULT_VIEW_ID_ROOT_DING_DESC"),
		example: t("DEFAULT_VIEW_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "userID",
		group: "",
		title: t("USER_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("USER_ID_ROOT_DING_DESC"),
		example: t("USER_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "syncContentToPageBlocks",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_CONTENT_TO_PAGE_BLOCKS_VAULT_TITLE"),
		platforms: ["Notion"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SYNC_CONTENT_TO_PAGE_BLOCKS_VAULT_DESC"),
	},
	{
		name: "pullContentFromPageBlocks",
		group: "Basic",
		groupOrder: 1,
		title: t("PULL_CONTENT_FROM_PAGE_BLOCKS_VAULT_TITLE"),
		platforms: ["Notion"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("PULL_CONTENT_FROM_PAGE_BLOCKS_VAULT_DESC"),
	},
	{
		name: "keepContentProperty",
		group: "Basic",
		groupOrder: 1,
		title: t("KEEP_CONTENT_PROPERTY_VAULT_TITLE"),
		platforms: ["Notion"],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("KEEP_CONTENT_PROPERTY_VAULT_DESC"),
	},
	{
		name: "contentAppendFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("CONTENT_APPEND_FIELDS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("CONTENT_APPEND_FIELDS_VAULT_DESC"),
		example: t("CONTENT_APPEND_FIELDS_VAULT_EXAMPLE"),
	},
	{
		name: "contentFetchField",
		group: "Basic",
		groupOrder: 1,
		title: t("CONTENT_FETCH_FIELD_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: t("CONTENT"),
		valueType: "string",
		description: t("CONTENT_FETCH_FIELD_VAULT_DESC"),
		example: t("CONTENT_FETCH_FIELD_VAULT_EXAMPLE"),
	},
	{
		name: "baseUrl",
		group: "",
		title: t("BASE_URL_ROOT_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Root",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("BASE_URL_ROOT_NOCODB_DESC"),
		example: t("BASE_URL_ROOT_NOCODB_EXAMPLE"),
	},
	{
		name: "apiUrlRoot",
		group: "",
		title: t("API_URL_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("API_URL_ROOT_BASEROW_DESC"),
		example: t("API_URL_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "recordUrlRoot",
		group: "",
		title: t("RECORD_URL_ROOT_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Root",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("RECORD_URL_ROOT_BASEROW_DESC"),
		example: t("RECORD_URL_ROOT_BASEROW_EXAMPLE"),
	},
	{
		name: "apiUrlRoot",
		group: "",
		title: t("API_URL_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("API_URL_ROOT_VIKA_DESC"),
		example: t("API_URL_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "recordUrlRoot",
		group: "",
		title: t("RECORD_URL_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("RECORD_URL_ROOT_VIKA_DESC"),
		example: t("RECORD_URL_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "customFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("CUSTOM_FIELDS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("CUSTOM_FIELDS_VAULT_DESC"),
		example: t("CUSTOM_FIELDS_VAULT_EXAMPLE"),
	},
	{
		name: "enableDateFilterForBatchSync",
		group: "Basic",
		groupOrder: 1,
		title: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_VAULT_DESC"),
		example: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_VAULT_EXAMPLE"),
	},
	{
		name: "enableUpdateFromDB",
		group: "Basic",
		groupOrder: 1,
		title: t("ENABLE_UPDATE_FROM_DB_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("ENABLE_UPDATE_FROM_DB_VAULT_DESC"),
		example: t("ENABLE_UPDATE_FROM_DB_VAULT_EXAMPLE"),
	},
	{
		name: "enableUpdatePropertiesFromDowloadTable",
		group: "Advanced",
		groupOrder: 2,
		title: t("ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t(
			"ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_VAULT_DESC",
		),
		example: t("ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_VAULT_EXAMPLE"),
	},
	{
		name: "extractBlocks",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_BLOCKS_VAULT_DESC"),
		example: t("EXTRACT_BLOCKS_VAULT_EXAMPLE"),
	},
	{
		name: "extractBlocksAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_AIRTABLE_DESC"),
		example: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractBlocksAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_DESC"),
		example: t("EXTRACT_BLOCKS_AS_TEXT_VAULT_EXAMPLE"),
	},
	{
		name: "extractKeyPoints",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_KEY_POINTS_VAULT_DESC"),
		example: t("EXTRACT_KEY_POINTS_VAULT_EXAMPLE"),
	},
	{
		name: "extractKeyPointsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_AIRTABLE_DESC"),
		example: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractKeyPointsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_DESC"),
		example: t("EXTRACT_KEY_POINTS_AS_TEXT_VAULT_EXAMPLE"),
	},
	{
		name: "extractSections",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_SECTIONS_VAULT_DESC"),
		example: t("EXTRACT_SECTIONS_VAULT_EXAMPLE"),
	},
	{
		name: "extractSectionsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_DESC"),
		example: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_EXAMPLE"),
	},
	{
		name: "extractSectionsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_AIRTABLE_DESC"),
		example: t("EXTRACT_SECTIONS_AS_TEXT_VAULT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractTagLines",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_TAG_LINES_VAULT_DESC"),
		example: t("EXTRACT_TAG_LINES_VAULT_EXAMPLE"),
	},
	{
		name: "extractTagLinesAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_DESC"),
		example: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_EXAMPLE"),
	},
	{
		name: "extractTagLinesAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_AIRTABLE_DESC"),
		example: t("EXTRACT_TAG_LINES_AS_TEXT_VAULT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "fieldsNames",
		group: "Advanced",
		groupOrder: 2,
		title: t("FIELDS_NAMES_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("FIELDS_NAMES_VAULT_DESC"),
		example: t("FIELDS_NAMES_VAULT_EXAMPLE"),
	},
	{
		name: "fmFetchFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("FM_FETCH_FIELDS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("FM_FETCH_FIELDS_VAULT_DESC"),
		example: t("FM_FETCH_FIELDS_VAULT_EXAMPLE"),
	},
	{
		name: "includesTagsInContent",
		group: "Basic",
		groupOrder: 1,
		title: t("INCLUDES_TAGS_IN_CONTENT_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("INCLUDES_TAGS_IN_CONTENT_VAULT_DESC"),
		example: t("INCLUDES_TAGS_IN_CONTENT_VAULT_EXAMPLE"),
	},
	{
		name: "justUpdateFromDB",
		group: "Basic",
		groupOrder: 1,
		title: t("JUST_UPDATE_FROM_DB_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("JUST_UPDATE_FROM_DB_VAULT_DESC"),
		example: t("JUST_UPDATE_FROM_DB_VAULT_EXAMPLE"),
	},
	{
		name: "sectionHeadingWholeMatch",
		group: "Extract",
		groupOrder: 3,
		title: t("SECTION_HEADING_WHOLE_MATCH_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SECTION_HEADING_WHOLE_MATCH_VAULT_DESC"),
		example: t("SECTION_HEADING_WHOLE_MATCH_VAULT_EXAMPLE"),
	},
	{
		name: "showDeleteOption",
		group: "Basic",
		groupOrder: 1,
		title: t("SHOW_DELETE_OPTION_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SHOW_DELETE_OPTION_VAULT_DESC"),
		example: t("SHOW_DELETE_OPTION_VAULT_EXAMPLE"),
	},
	{
		name: "sortFrontMatterProperties",
		group: "Basic",
		groupOrder: 1,
		title: t("SORT_FRONT_MATTER_PROPERTIES_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SORT_FRONT_MATTER_PROPERTIES_VAULT_DESC"),
		example: t("SORT_FRONT_MATTER_PROPERTIES_VAULT_EXAMPLE"),
	},
	{
		name: "syncContent",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_CONTENT_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SYNC_CONTENT_VAULT_DESC"),
		example: t("SYNC_CONTENT_VAULT_EXAMPLE"),
	},
	{
		name: "syncFullContent",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_FULL_CONTENT_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SYNC_FULL_CONTENT_VAULT_DESC"),
		example: t("SYNC_FULL_CONTENT_VAULT_EXAMPLE"),
	},
	{
		name: "syncMode",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_MODE_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "id",
		valueType: "string",
		description: t("SYNC_MODE_VAULT_DESC"),
		example: t("SYNC_MODE_VAULT_EXAMPLE"),
	},
	{
		name: "syncOptions",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_OPTIONS_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("SYNC_OPTIONS_VAULT_DESC"),
		example: t("SYNC_OPTIONS_VAULT_EXAMPLE"),
	},
	{
		name: "useTitleInDb",
		group: "Basic",
		groupOrder: 1,
		title: t("USE_TITLE_IN_DB_VAULT_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Vault",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("USE_TITLE_IN_DB_VAULT_DESC"),
		example: t("USE_TITLE_IN_DB_VAULT_EXAMPLE"),
	},
	{
		name: "baseID",
		group: "Basic",
		groupOrder: 1,
		title: t("BASE_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("BASE_ID_FOLDER_DING_DESC"),
		example: t("BASE_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "fileID",
		group: "Basic",
		groupOrder: 1,
		title: t("FILE_ID_FOLDER_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FILE_ID_FOLDER_WPS_DESC"),
		example: t("FILE_ID_FOLDER_WPS_EXAMPLE"),
	},
	{
		name: "folderName",
		group: "Basic",
		groupOrder: 1,
		title: t("FOLDER_NAME_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FOLDER_NAME_FOLDER_DESC"),
		example: t("FOLDER_NAME_FOLDER_EXAMPLE"),
	},
	{
		name: "sheetID",
		group: "Basic",
		groupOrder: 1,
		title: t("SHEET_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("SHEET_ID_FOLDER_DING_DESC"),
		example: t("SHEET_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "sheetID",
		group: "Basic",
		groupOrder: 1,
		title: t("SHEET_ID_FOLDER_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("SHEET_ID_FOLDER_WPS_DESC"),
		example: t("SHEET_ID_FOLDER_WPS_EXAMPLE"),
	},
	{
		name: "tableID",
		group: "Basic",
		groupOrder: 1,
		title: t("TABLE_ID_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("TABLE_ID_FOLDER_AIRTABLE_DESC"),
		example: t("TABLE_ID_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "dataSourceID",
		group: "Basic",
		groupOrder: 1,
		title: t("DATA_SOURCE_ID_FOLDER_NOTION_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("DATA_SOURCE_ID_FOLDER_NOTION_DESC"),
		example: t("DATA_SOURCE_ID_FOLDER_NOTION_EXAMPLE"),
	},
	{
		name: "tableID",
		group: "Basic",
		groupOrder: 1,
		title: t("TABLE_ID_FOLDER_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("TABLE_ID_FOLDER_BASEROW_DESC"),
		example: t("TABLE_ID_FOLDER_BASEROW_EXAMPLE"),
	},
	{
		name: "tableID",
		group: "Basic",
		groupOrder: 1,
		title: t("TABLE_ID_FOLDER_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("TABLE_ID_FOLDER_NOCODB_DESC"),
		example: t("TABLE_ID_FOLDER_NOCODB_EXAMPLE"),
	},
	{
		name: "tableID",
		group: "Basic",
		groupOrder: 1,
		title: t("TABLE_ID_FOLDER_TITLE"),
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("TABLE_ID_FOLDER_DESC"),
		example: t("TABLE_ID_FOLDER_EXAMPLE"),
	},
	{
		name: "tableID",
		group: "Basic",
		groupOrder: 1,
		title: t("TABLE_ID_FOLDER_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("TABLE_ID_FOLDER_VIKA_DESC"),
		example: t("TABLE_ID_FOLDER_VIKA_EXAMPLE"),
	},
	{
		name: "viewID",
		group: "Basic",
		groupOrder: 1,
		title: t("VIEW_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("VIEW_ID_FOLDER_DING_DESC"),
		example: t("VIEW_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "appToken",
		group: "Basic",
		groupOrder: 1,
		title: t("APP_TOKEN_FOLDER_TITLE"),
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("APP_TOKEN_FOLDER_DESC"),
		example: t("APP_TOKEN_FOLDER_EXAMPLE"),
	},
	{
		name: "baseID",
		group: "Basic",
		groupOrder: 1,
		title: t("BASE_ID_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("BASE_ID_FOLDER_AIRTABLE_DESC"),
		example: t("BASE_ID_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "baseID",
		group: "Basic",
		groupOrder: 1,
		title: t("BASE_ID_FOLDER_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("BASE_ID_FOLDER_BASEROW_DESC"),
		example: t("BASE_ID_FOLDER_BASEROW_EXAMPLE"),
	},
	{
		name: "baseID",
		group: "Basic",
		groupOrder: 1,
		title: t("BASE_ID_FOLDER_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("BASE_ID_FOLDER_NOCODB_DESC"),
		example: t("BASE_ID_FOLDER_NOCODB_EXAMPLE"),
	},
	{
		name: "apiKey",
		group: "Basic",
		groupOrder: 1,
		title: t("API_KEY_FOLDER_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("API_KEY_FOLDER_DESC"),
		example: t("API_KEY_FOLDER_EXAMPLE"),
	},
	{
		name: "syncContentToPageBlocks",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_CONTENT_TO_PAGE_BLOCKS_FOLDER_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SYNC_CONTENT_TO_PAGE_BLOCKS_FOLDER_DESC"),
	},
	{
		name: "pullContentFromPageBlocks",
		group: "Basic",
		groupOrder: 1,
		title: t("PULL_CONTENT_FROM_PAGE_BLOCKS_FOLDER_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("PULL_CONTENT_FROM_PAGE_BLOCKS_FOLDER_DESC"),
	},
	{
		name: "keepContentProperty",
		group: "Basic",
		groupOrder: 1,
		title: t("KEEP_CONTENT_PROPERTY_FOLDER_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("KEEP_CONTENT_PROPERTY_FOLDER_DESC"),
	},
	{
		name: "contentAppendFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("CONTENT_APPEND_FIELDS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("CONTENT_APPEND_FIELDS_FOLDER_DESC"),
		example: t("CONTENT_APPEND_FIELDS_FOLDER_EXAMPLE"),
	},
	{
		name: "contentFetchField",
		group: "Advanced",
		groupOrder: 2,
		title: t("CONTENT_FETCH_FIELD_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: t("CONTENT"),
		valueType: "string",
		description: t("CONTENT_FETCH_FIELD_FOLDER_DESC"),
		example: t("CONTENT_FETCH_FIELD_FOLDER_EXAMPLE"),
	},
	{
		name: "customFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("CUSTOM_FIELDS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("CUSTOM_FIELDS_FOLDER_DESC"),
		example: t("CUSTOM_FIELDS_FOLDER_EXAMPLE"),
	},
	{
		name: "customFieldsOverrideMode",
		group: "Advanced",
		groupOrder: 2,
		title: t("CUSTOM_FIELDS_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("CUSTOM_FIELDS_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("CUSTOM_FIELDS_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	{
		name: "downloadAppToken",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_APP_TOKEN_FOLDER_TITLE"),
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_APP_TOKEN_FOLDER_DESC"),
		example: t("DOWNLOAD_APP_TOKEN_FOLDER_EXAMPLE"),
	},
	{
		name: "downloadBaseID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_BASE_ID_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_BASE_ID_FOLDER_AIRTABLE_DESC"),
		example: t("DOWNLOAD_BASE_ID_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "downloadBaseID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_BASE_ID_FOLDER_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_BASE_ID_FOLDER_BASEROW_DESC"),
		example: t("DOWNLOAD_BASE_ID_FOLDER_BASEROW_EXAMPLE"),
	},
	{
		name: "downloadBaseID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_BASE_ID_FOLDER_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_BASE_ID_FOLDER_NOCODB_DESC"),
		example: t("DOWNLOAD_BASE_ID_FOLDER_NOCODB_EXAMPLE"),
	},
	{
		name: "downloadBaseID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_BASE_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_BASE_ID_FOLDER_DING_DESC"),
		example: t("DOWNLOAD_BASE_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "downloadFileID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_FILE_ID_FOLDER_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_FILE_ID_FOLDER_WPS_DESC"),
		example: t("DOWNLOAD_FILE_ID_FOLDER_WPS_EXAMPLE"),
	},
	{
		name: "downloadSheetID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_SHEET_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_SHEET_ID_FOLDER_DING_DESC"),
		example: t("DOWNLOAD_SHEET_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "downloadSheetID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_SHEET_ID_FOLDER_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_SHEET_ID_FOLDER_WPS_DESC"),
		example: t("DOWNLOAD_SHEET_ID_FOLDER_WPS_EXAMPLE"),
	},
	{
		name: "downloadTableID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_TABLE_ID_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_TABLE_ID_FOLDER_AIRTABLE_DESC"),
		example: t("DOWNLOAD_TABLE_ID_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "downloadDataSourceID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_DATA_SOURCE_ID_FOLDER_NOTION_TITLE"),
		platforms: ["Notion"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_DATA_SOURCE_ID_FOLDER_NOTION_DESC"),
		example: t("DOWNLOAD_DATA_SOURCE_ID_FOLDER_NOTION_EXAMPLE"),
	},
	{
		name: "downloadTableID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_TABLE_ID_FOLDER_BASEROW_TITLE"),
		platforms: ["Baserow"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_TABLE_ID_FOLDER_BASEROW_DESC"),
		example: t("DOWNLOAD_TABLE_ID_FOLDER_BASEROW_EXAMPLE"),
	},
	{
		name: "downloadTableID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_TABLE_ID_FOLDER_NOCODB_TITLE"),
		platforms: ["NocoDB"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_TABLE_ID_FOLDER_NOCODB_DESC"),
		example: t("DOWNLOAD_TABLE_ID_FOLDER_NOCODB_EXAMPLE"),
	},
	{
		name: "downloadTableID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_TABLE_ID_FOLDER_TITLE"),
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_TABLE_ID_FOLDER_DESC"),
		example: t("DOWNLOAD_TABLE_ID_FOLDER_EXAMPLE"),
	},
	{
		name: "downloadTableID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_TABLE_ID_FOLDER_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_TABLE_ID_FOLDER_VIKA_DESC"),
		example: t("DOWNLOAD_TABLE_ID_FOLDER_VIKA_EXAMPLE"),
	},
	{
		name: "downloadViewID",
		group: "Basic",
		groupOrder: 1,
		title: t("DOWNLOAD_VIEW_ID_FOLDER_DING_TITLE"),
		platforms: ["Ding"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("DOWNLOAD_VIEW_ID_FOLDER_DING_DESC"),
		example: t("DOWNLOAD_VIEW_ID_FOLDER_DING_EXAMPLE"),
	},
	{
		name: "enableDateFilterForBatchSync",
		group: "Basic",
		groupOrder: 1,
		title: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_FOLDER_DESC"),
		example: t("ENABLE_DATE_FILTER_FOR_BATCH_SYNC_FOLDER_EXAMPLE"),
	},
	{
		name: "enableUpdateFromDB",
		group: "Basic",
		groupOrder: 1,
		title: t("ENABLE_UPDATE_FROM_DB_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("ENABLE_UPDATE_FROM_DB_FOLDER_DESC"),
		example: t("ENABLE_UPDATE_FROM_DB_FOLDER_EXAMPLE"),
	},
	{
		name: "enableUpdatePropertiesFromDowloadTable",
		group: "Basic",
		groupOrder: 1,
		title: t("ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t(
			"ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_FOLDER_DESC",
		),
		example: t(
			"ENABLE_UPDATE_PROPERTIES_FROM_DOWLOAD_TABLE_FOLDER_EXAMPLE",
		),
	},
	// Extract Section
	{
		name: "extractSections",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_SECTIONS_FOLDER_DESC"),
		example: t("EXTRACT_SECTIONS_FOLDER_EXAMPLE"),
	},
	{
		name: "extractSectionsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_DESC"),
		example: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_EXAMPLE"),
	},
	{
		name: "extractSectionsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_AIRTABLE_DESC"),
		example: t("EXTRACT_SECTIONS_AS_TEXT_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractSectionsOverrideMode",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_SECTIONS_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_SECTIONS_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("EXTRACT_SECTIONS_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	// Extract Block
	{
		name: "extractBlocks",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_BLOCKS_FOLDER_DESC"),
		example: t("EXTRACT_BLOCKS_FOLDER_EXAMPLE"),
	},
	{
		name: "extractBlocksAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_AIRTABLE_DESC"),
		example: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractBlocksAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_DESC"),
		example: t("EXTRACT_BLOCKS_AS_TEXT_FOLDER_EXAMPLE"),
	},
	{
		name: "extractBlocksOverrideMode",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_BLOCKS_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_BLOCKS_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("EXTRACT_BLOCKS_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	// Extract Tag Line
	{
		name: "extractTagLines",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_TAG_LINES_FOLDER_DESC"),
		example: t("EXTRACT_TAG_LINES_FOLDER_EXAMPLE"),
	},
	{
		name: "extractTagLinesAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_DESC"),
		example: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_EXAMPLE"),
	},
	{
		name: "extractTagLinesAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_AIRTABLE_DESC"),
		example: t("EXTRACT_TAG_LINES_AS_TEXT_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractTagLinesOverrideMode",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_TAG_LINES_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_TAG_LINES_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("EXTRACT_TAG_LINES_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	// Extract Key Point
	{
		name: "extractKeyPoints",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("EXTRACT_KEY_POINTS_FOLDER_DESC"),
		example: t("EXTRACT_KEY_POINTS_FOLDER_EXAMPLE"),
	},
	{
		name: "extractKeyPointsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_AIRTABLE_DESC"),
		example: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "extractKeyPointsAsText",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_TITLE"),
		platforms: [
			"Vika",
			"Feishu",
			"Lark",
			"WPS",
			"Ding",
			"Baserow",
			"NocoDB",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_DESC"),
		example: t("EXTRACT_KEY_POINTS_AS_TEXT_FOLDER_EXAMPLE"),
	},
	{
		name: "extractKeyPointsOverrideMode",
		group: "Extract",
		groupOrder: 3,
		title: t("EXTRACT_KEY_POINTS_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("EXTRACT_KEY_POINTS_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("EXTRACT_KEY_POINTS_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	// Fetch Fields
	{
		name: "fmFetchFields",
		group: "Advanced",
		groupOrder: 2,
		title: t("FM_FETCH_FIELDS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("FM_FETCH_FIELDS_FOLDER_DESC"),
		example: t("FM_FETCH_FIELDS_FOLDER_EXAMPLE"),
	},
	{
		name: "fmFetchFieldsOverrideMode",
		group: "Advanced",
		groupOrder: 2,
		title: t("FM_FETCH_FIELDS_OVERRIDE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("FM_FETCH_FIELDS_OVERRIDE_MODE_FOLDER_DESC"),
		example: t("FM_FETCH_FIELDS_OVERRIDE_MODE_FOLDER_EXAMPLE"),
	},
	{
		name: "includesTagsInContent",
		group: "Basic",
		groupOrder: 1,
		title: t("INCLUDES_TAGS_IN_CONTENT_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("INCLUDES_TAGS_IN_CONTENT_FOLDER_DESC"),
		example: t("INCLUDES_TAGS_IN_CONTENT_FOLDER_EXAMPLE"),
	},
	{
		name: "justUpdateFromDB",
		group: "Basic",
		groupOrder: 1,
		title: t("JUST_UPDATE_FROM_DB_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("JUST_UPDATE_FROM_DB_FOLDER_DESC"),
		example: t("JUST_UPDATE_FROM_DB_FOLDER_EXAMPLE"),
	},
	{
		name: "pullContentOnly",
		group: "Basic",
		groupOrder: 1,
		title: t("PULL_CONTENT_ONLY_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("PULL_CONTENT_ONLY_FOLDER_DESC"),
		example: t("PULL_CONTENT_ONLY_FOLDER_EXAMPLE"),
	},
	{
		name: "sectionHeadingWholeMatch",
		group: "Extract",
		groupOrder: 3,
		title: t("SECTION_HEADING_WHOLE_MATCH_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SECTION_HEADING_WHOLE_MATCH_FOLDER_DESC"),
		example: t("SECTION_HEADING_WHOLE_MATCH_FOLDER_EXAMPLE"),
	},
	{
		name: "separateMode",
		group: "Advanced",
		groupOrder: 2,
		title: t("SEPARATE_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SEPARATE_MODE_FOLDER_DESC"),
		example: t("SEPARATE_MODE_FOLDER_EXAMPLE"),
	},
	{
		name: "showDeleteOption",
		group: "Basic",
		groupOrder: 1,
		title: t("SHOW_DELETE_OPTION_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SHOW_DELETE_OPTION_FOLDER_DESC"),
		example: t("SHOW_DELETE_OPTION_FOLDER_EXAMPLE"),
	},
	{
		name: "sortFrontMatterProperties",
		group: "Basic",
		groupOrder: 1,
		title: t("SORT_FRONT_MATTER_PROPERTIES_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SORT_FRONT_MATTER_PROPERTIES_FOLDER_DESC"),
		example: t("SORT_FRONT_MATTER_PROPERTIES_FOLDER_EXAMPLE"),
	},
	{
		name: "syncContent",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_CONTENT_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "true",
		valueType: "boolean",
		description: t("SYNC_CONTENT_FOLDER_DESC"),
		example: t("SYNC_CONTENT_FOLDER_EXAMPLE"),
	},
	{
		name: "syncFullContent",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_FULL_CONTENT_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("SYNC_FULL_CONTENT_FOLDER_DESC"),
		example: t("SYNC_FULL_CONTENT_FOLDER_EXAMPLE"),
	},
	{
		name: "syncMode",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_MODE_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "id",
		valueType: "string",
		description: t("SYNC_MODE_FOLDER_DESC"),
		example: t("SYNC_MODE_FOLDER_EXAMPLE"),
	},
	{
		name: "syncOptions",
		group: "Basic",
		groupOrder: 1,
		title: t("SYNC_OPTIONS_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "[]",
		valueType: "array",
		description: t("SYNC_OPTIONS_FOLDER_DESC"),
		example: t("SYNC_OPTIONS_FOLDER_EXAMPLE"),
	},
	{
		name: "useTitleInDb",
		group: "Basic",
		groupOrder: 1,
		title: t("USE_TITLE_IN_DB_FOLDER_TITLE"),
		platforms: [
			"Airtable",
			"Baserow",
			"NocoDB",
			"Feishu",
			"Vika",
			"Lark",
			"WPS",
			"Ding",
			"Notion",
		],
		level: "Folder",
		required: false,
		defaultValue: "false",
		valueType: "boolean",
		description: t("USE_TITLE_IN_DB_FOLDER_DESC"),
		example: t("USE_TITLE_IN_DB_FOLDER_EXAMPLE"),
	},
];
