import { FetchOption } from "./types";
import { t } from "./lang/helpers";

export const FETCH_SCRIPT_GENERATOR_VIEW_TYPE = "fetch-script-generator-view";

export const FETCH_OPTIONS: FetchOption[] = [
	{
		name: "accessToken",

		title: t("FETCH_ACCESS_TOKEN_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_ACCESS_TOKEN_ROOT_WPS_DESC"),
		example: t("FETCH_ACCESS_TOKEN_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "apiKey",

		title: t("FETCH_API_KEY_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_API_KEY_ROOT_AIRTABLE_DESC"),
		example: t("FETCH_API_KEY_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "apiKey",

		title: t("FETCH_API_KEY_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_API_KEY_ROOT_VIKA_DESC"),
		example: t("FETCH_API_KEY_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "appID",

		title: t("FETCH_APP_ID_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_ID_ROOT_FEISHU_DESC"),
		example: t("FETCH_APP_ID_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "appID",

		title: t("FETCH_APP_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_ID_ROOT_DING_DESC"),
		example: t("FETCH_APP_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "appID",

		title: t("FETCH_APP_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_ID_ROOT_WPS_DESC"),
		example: t("FETCH_APP_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "appID",

		title: t("FETCH_APP_ID_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_ID_ROOT_LARK_DESC"),
		example: t("FETCH_APP_ID_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "appKey",

		title: t("FETCH_APP_KEY_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_KEY_ROOT_WPS_DESC"),
		example: t("FETCH_APP_KEY_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "appSecret",

		title: t("FETCH_APP_SECRET_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_SECRET_ROOT_FEISHU_DESC"),
		example: t("FETCH_APP_SECRET_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "appSecret",

		title: t("FETCH_APP_SECRET_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_SECRET_ROOT_DING_DESC"),
		example: t("FETCH_APP_SECRET_ROOT_DING_EXAMPLE"),
	},
	{
		name: "appSecret",

		title: t("FETCH_APP_SECRET_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_SECRET_ROOT_LARK_DESC"),
		example: t("FETCH_APP_SECRET_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultAppToken",

		title: t("FETCH_DEFAULT_APP_TOKEN_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_APP_TOKEN_ROOT_FEISHU_DESC"),
		example: t("FETCH_DEFAULT_APP_TOKEN_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "defaultAppToken",

		title: t("FETCH_DEFAULT_APP_TOKEN_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_APP_TOKEN_ROOT_LARK_DESC"),
		example: t("FETCH_DEFAULT_APP_TOKEN_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultBaseID",

		title: t("FETCH_DEFAULT_BASE_ID_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_BASE_ID_ROOT_AIRTABLE_DESC"),
		example: t("FETCH_DEFAULT_BASE_ID_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "defaultBaseID",

		title: t("FETCH_DEFAULT_BASE_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_BASE_ID_ROOT_DING_DESC"),
		example: t("FETCH_DEFAULT_BASE_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "defaultFileID",

		title: t("FETCH_DEFAULT_FILE_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_FILE_ID_ROOT_WPS_DESC"),
		example: t("FETCH_DEFAULT_FILE_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "defaultSheetID",

		title: t("FETCH_DEFAULT_SHEET_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_SHEET_ID_ROOT_DING_DESC"),
		example: t("FETCH_DEFAULT_SHEET_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "defaultSheetID",

		title: t("FETCH_DEFAULT_SHEET_ID_ROOT_WPS_TITLE"),
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_SHEET_ID_ROOT_WPS_DESC"),
		example: t("FETCH_DEFAULT_SHEET_ID_ROOT_WPS_EXAMPLE"),
	},
	{
		name: "defaultTableID",

		title: t("FETCH_DEFAULT_TABLE_ID_ROOT_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_TABLE_ID_ROOT_AIRTABLE_DESC"),
		example: t("FETCH_DEFAULT_TABLE_ID_ROOT_AIRTABLE_EXAMPLE"),
	},
	{
		name: "defaultTableID",

		title: t("FETCH_DEFAULT_TABLE_ID_ROOT_FEISHU_TITLE"),
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_TABLE_ID_ROOT_FEISHU_DESC"),
		example: t("FETCH_DEFAULT_TABLE_ID_ROOT_FEISHU_EXAMPLE"),
	},
	{
		name: "defaultTableID",

		title: t("FETCH_DEFAULT_TABLE_ID_ROOT_VIKA_TITLE"),
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_TABLE_ID_ROOT_VIKA_DESC"),
		example: t("FETCH_DEFAULT_TABLE_ID_ROOT_VIKA_EXAMPLE"),
	},
	{
		name: "defaultTableID",

		title: t("FETCH_DEFAULT_TABLE_ID_ROOT_LARK_TITLE"),
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_TABLE_ID_ROOT_LARK_DESC"),
		example: t("FETCH_DEFAULT_TABLE_ID_ROOT_LARK_EXAMPLE"),
	},
	{
		name: "defaultViewID",

		title: t("FETCH_DEFAULT_VIEW_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_DEFAULT_VIEW_ID_ROOT_DING_DESC"),
		example: t("FETCH_DEFAULT_VIEW_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "userID",

		title: t("FETCH_USER_ID_ROOT_DING_TITLE"),
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_USER_ID_ROOT_DING_DESC"),
		example: t("FETCH_USER_ID_ROOT_DING_EXAMPLE"),
	},
	{
		name: "fieldsNames",

		title: t("FETCH_VAULT_FIELDS_NAMES_TITLE"),
		platforms: ["Airtable", "Feishu", "Vika", "Lark", "WPS", "Ding"],
		level: "Vault",
		required: false,
		defaultValue: "{}",
		valueType: "object",
		description: t("FETCH_VAULT_FIELDS_NAMES_DESC"),
		example: t("FETCH_VAULT_FIELDS_NAMES_EXAMPLE"),
	},
	{
		name: "sourceName",

		title: t("FETCH_SOURCE_NAME_FOLDER_TITLE"),
		platforms: ["Airtable", "Feishu", "Vika", "Lark", "WPS", "Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_SOURCE_NAME_FOLDER_DESC"),
		example: t("FETCH_SOURCE_NAME_FOLDER_EXAMPLE"),
	},
	{
		name: "targetFolderPath",

		title: t("FETCH_TARGET_FOLDER_FOLDER_TITLE"),
		platforms: ["Airtable", "Feishu", "Vika", "Lark", "WPS", "Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_TARGET_FOLDER_FOLDER_DESC"),
		example: t("FETCH_TARGET_FOLDER_FOLDER_EXAMPLE"),
	},
	{
		name: "baseID",
		title: t("FETCH_BASE_ID_FOLDER_AIRTABLE_TITLE"),
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_BASE_ID_FOLDER_AIRTABLE_DESC"),
		example: t("FETCH_BASE_ID_FOLDER_AIRTABLE_EXAMPLE"),
	},
	{
		name: "appToken",

		title: t("FETCH_APP_TOKEN_FOLDER_TITLE"),
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_APP_TOKEN_FOLDER_DESC"),
		example: t("FETCH_APP_TOKEN_FOLDER_EXAMPLE"),
	},
	{
		name: "tableID",

		title: t("FETCH_TABLE_ID_FOLDER_TITLE"),
		platforms: ["Airtable", "Vika", "Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_TABLE_ID_FOLDER_DESC"),
		example: t("FETCH_TABLE_ID_FOLDER_EXAMPLE"),
	},
	{
		name: "viewID",

		title: t("FETCH_VIEW_ID_FOLDER_TITLE"),
		platforms: ["Airtable", "Vika", "Feishu"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: t("FETCH_VIEW_ID_FOLDER_DESC"),
		example: t("FETCH_VIEW_ID_FOLDER_EXAMPLE"),
	},
];
