import { FetchOption } from "./types";

export const FETCH_SCRIPT_GENERATOR_VIEW_TYPE = "fetch-script-generator-view";

export const FETCH_OPTIONS: FetchOption[] = [
	{
		name: "accessToken",

		title: "Access Token",
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "WPS的用户Access Token",
		example: "Fetch设置时默认使用：\n${wpsUserTokenForFetch}",
	},
	{
		name: "apiKey",

		title: "Api Key",
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description:
			"从Airtable获取数据时，必须提供一个相应的API Key。\n\n其中，Airtable的API Key，已经升级为Personal Access Token。",
		example: "Fetch设置时使用：\n${airtableAPIKeyForFetch}",
	},
	{
		name: "apiKey",

		title: "Api Key",
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Vika获取数据时，必须提供一个相应的API Key。",
		example: "Fetch设置时默认使用：\n${vikaAPIKeyForFetch}",
	},
	{
		name: "appID",

		title: "App ID",
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从飞书获取数据时，需要提供自建应用的APP ID",
		example: "Fetch设置时默认使用：\n${feishuAppIDForFetch}",
	},
	{
		name: "appID",

		title: "App ID",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，需要提供自建应用的App ID",
		example: "Fetch设置时默认使用：\n${dingAppIDForFetch}",
	},
	{
		name: "appID",

		title: "App ID",
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从WPS获取数据时，需要提供自建应用的App ID",
		example: "Fetch设置时默认使用：\n${wpsAppIDForFetch}",
	},
	{
		name: "appID",

		title: "App ID",
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Lark获取数据时，需要提供自建应用的APP ID",
		example: "Fetch设置时默认使用：\n${larkAppIDForFetch}",
	},
	{
		name: "appKey",

		title: "App Key",
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从WPS获取数据时，需要提供自建应用的APP Key",
		example: "Fetch设置时默认使用：\n${wpsAppSecretForFetch}",
	},
	{
		name: "appSecret",

		title: "App Secret",
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从飞书获取数据时，需要提供自建应用的APP Secret",
		example: "Fetch设置时默认使用：\n${feishuAppSecretForFetch}",
	},
	{
		name: "appSecret",

		title: "App Secret",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，需要提供自建应用的App Secret",
		example: "Fetch设置时默认使用：\n${dingAppSecretForFetch}",
	},
	{
		name: "appSecret",

		title: "App Secret",
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Lark获取数据时，需要提供自建应用的APP Secret",
		example: "Fetch设置时默认使用：\n${larkAppSecretForFetch}",
	},
	{
		name: "defaultAppToken",

		title: "Default App Token",
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description:
			"从飞书获取数据时，默认使用的多维表的App Token。\n\n多维表的App Token，相当于Airtable中的Base ID。",
		example: "Fetch设置时默认使用：\n${feishuBaseIDForFetch}",
	},
	{
		name: "defaultAppToken",

		title: "Default App Token",
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description:
			"从Lark获取数据时，默认使用的多维表的App Token。\n\n多维表的App Token，相当于Airtable中的Base ID。",
		example: "Fetch设置时默认使用：\n${larkBaseIDForFetch}",
	},
	{
		name: "defaultBaseID",

		title: "Default Base ID",
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Airtable获取数据时，默认使用的Base ID。",
		example: "Fetch设置时默认使用：\n${airtableBaseIDForFetch}",
	},
	{
		name: "defaultBaseID",

		title: "Default Base ID",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，默认使用的AI表格的Base ID",
		example: "Fetch设置时默认使用：\n${dingBaseIDForFetch}",
	},
	{
		name: "defaultFileID",

		title: "Default File ID",
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从WPS获取数据时，默认使用的多维表文件ID",
		example: "Fetch设置时默认使用：\n${wpsBaseIDForFetch}",
	},
	{
		name: "defaultSheetID",

		title: "Default Sheet ID",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，默认使用的AI表格的Sheet ID",
		example: "Fetch设置时默认使用：\n${dingTableIDForFetch}",
	},
	{
		name: "defaultSheetID",

		title: "Default Sheet ID",
		platforms: ["WPS"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从WPS获取数据时，默认使用的多维表Sheet ID",
		example: "Fetch设置时默认使用：\n${wpsTableIDForFetch}",
	},
	{
		name: "defaultTableID",

		title: "Default Table ID",
		platforms: ["Airtable"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Airtable获取数据时，默认使用的Table ID。",
		example: "Fetch设置时默认使用：\n${airtableTableIDForFetch}",
	},
	{
		name: "defaultTableID",

		title: "Default Table ID",
		platforms: ["Feishu"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从飞书获取数据时，默认使用的Table ID。",
		example: "Fetch设置时默认使用：\n${feishuTableIDForFetch}",
	},
	{
		name: "defaultTableID",

		title: "Default Table ID",
		platforms: ["Vika"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Vika获取数据时，默认使用的Table ID。",
		example: "Fetch设置时默认使用：\n${vikaTableIDForFetch}",
	},
	{
		name: "defaultTableID",

		title: "Default Table ID",
		platforms: ["Lark"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从Lark获取数据时，默认使用的Table ID。",
		example: "Fetch设置时默认使用：\n${larkTableIDForFetch}",
	},
	{
		name: "defaultViewID",

		title: "Default View ID",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，默认使用的AI表格的View ID",
		example: "Fetch设置时默认使用：\n${dingViewIDForFetch}",
	},
	{
		name: "userID",

		title: "User ID",
		platforms: ["Ding"],
		level: "Root",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "从钉钉获取数据时，默认使用的通讯录中的用户ID",
		example: "Fetch设置时默认使用：\n${dingUserIDForFetch}",
	},
	{
		name: "sourceName",

		title: "Source Name",
		platforms: ["Airtable", "Feishu", "Vika", "Lark", "WPS", "Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "用户自定义的数据来源名",
		example: "我的闪念",
	},
	{
		name: "targetFolder",

		title: "Target Folder",
		platforms: ["Airtable", "Feishu", "Vika", "Lark", "WPS", "Ding"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "获取数据的存放路径",
		example: "2-输出/闪念",
	},
	{
		name: "baseID",
		title: "Base ID",
		platforms: ["Airtable"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: "数据源的Base ID，如果为空，使用默认的Base ID。",
		example: "appxxxxxx",
	},
	{
		name: "appToken",

		title: "App Token",
		platforms: ["Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: "数据源的App Token，如果为空，使用默认的App Token。",
		example: "appxxxxxx",
	},
	{
		name: "tableID",

		title: "Table ID",
		platforms: ["Airtable", "Vika", "Feishu", "Lark"],
		level: "Folder",
		required: false,
		defaultValue: "无",
		valueType: "string",
		description: "数据源的Table ID，如果为空，使用默认的Table ID。",
		example: "tblxxxxxx",
	},
	{
		name: "viewID",

		title: "View ID",
		platforms: ["Airtable", "Vika", "Feishu"],
		level: "Folder",
		required: true,
		defaultValue: "无",
		valueType: "string",
		description: "数据源的View ID",
		example: "vwxxxxxx",
	},
];
